version: '3.2'
services:

  elasticsearch:
    image: laraws/elasticsearch-ik:2.4.3
    container_name: elasticsearch2
    restart: unless-stopped
    tty: true
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  #Nginx Service
  kibana:
    image: kibana:4.6.0
    container_name: kibana2
    restart: unless-stopped
    tty: true
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:
    driver: bridge